version: '3.8'


services:

# Postgres DB
  db:
    image: postgres
    container_name: db
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    container_name: db_pg_admin
    image: dpage/pgadmin4
    restart: always
    env_file:
      - ./.env
    ports:
      - "5050:80"

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    entrypoint:
      [ "/app/docker-entrypoint.sh" ]
    env_file:
      - ./.env
    depends_on:
      - db


volumes:
  postgres_data:
