"""add/building_field

Revision ID: 07a62af4f985
Revises: 9812d4369099
Create Date: 2025-01-11 13:24:46.318328

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "07a62af4f985"
down_revision: Union[str, None] = "9812d4369099"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "organization", sa.Column("building_id", sa.Integer(), nullable=False)
    )
    op.create_foreign_key(
        None, "organization", "building", ["building_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "organization", type_="foreignkey")
    op.drop_column("organization", "building_id")
    # ### end Alembic commands ###
