"""add/organization_and_building_model

Revision ID: 9812d4369099
Revises: b248b0655e06
Create Date: 2025-01-11 13:13:35.849778

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9812d4369099"
down_revision: Union[str, None] = "b248b0655e06"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "building",
        sa.Column("address", sa.String(length=300), nullable=False),
        sa.Column(
            "latitude", sa.Numeric(precision=8, scale=6), nullable=False
        ),
        sa.Column(
            "longitude", sa.Numeric(precision=9, scale=6), nullable=False
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "latitude", "longitude", name="_building_location_uc"
        ),
    )
    op.create_table(
        "organizationactivity",
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column("activity_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["activity_id"],
            ["activity.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "organizationphonenumber",
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column("phone_number", sa.String(length=300), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.alter_column(
        "organization",
        "name",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.String(length=300),
        existing_nullable=False,
    )
    op.drop_constraint("organization_name_key", "organization", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "organization_name_key", "organization", ["name"]
    )
    op.alter_column(
        "organization",
        "name",
        existing_type=sa.String(length=300),
        type_=sa.VARCHAR(length=100),
        existing_nullable=False,
    )
    op.drop_table("organizationphonenumber")
    op.drop_table("organizationactivity")
    op.drop_table("building")
    # ### end Alembic commands ###
